import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdir,writeFile} from 'node:fs/promises';
import {setup} from './academy-portal.mjs';
const s=await setup(),{api,h,db,cookie,cupcake}=s,results=[];
const check=async(name,fn)=>{await fn();results.push({name,status:'PASS'});console.log('PASS',name);};
const recipeDocument={description:'Student-safe description',variants:[{name:'Main',yield:{quantity:'12',unit:'cookies'},groups:[{name:'Dough',ingredients:[{name:'Flour',quantity:'200',unit:'g'}]}],methods:[{name:'Mix',steps:[{instruction:'Mix gently'}]}]}]};
try{
 const recipe=await api(h.ids.owner,'save_recipe',{title:'Approved student recipe',document:recipeDocument});await api(h.ids.owner,'assign_recipe',{class_id:cookie.id,recipe_id:recipe.id});
 const foreign=await api(h.ids.owner,'save_recipe',{title:'Other class recipe',document:recipeDocument});await api(h.ids.owner,'assign_recipe',{class_id:cupcake.id,recipe_id:foreign.id});
 const module=await api(h.ids.owner,'save_module',{class_id:cupcake.id,name:'Other class module'});
 await check('Anonymous callers cannot use new UX reads',async()=>{for(const action of ['navigation','gallery_post','threads','thread_status'])await assert.rejects(api(null,action,{id:randomUUID()}));});
 await check('Navigation reveals only current assignments and no recipe documents',async()=>{const nav=await api(h.ids.customer,'navigation');assert.deepEqual(nav.classes,[{id:cookie.id,name:cookie.name||'Cookies & Brownies'}]);assert.equal(nav.admin,false);assert.equal(nav.instructor,false);assert.ok(!JSON.stringify(nav).includes('Student-safe description'));assert.deepEqual((await api(h.ids.unverified,'navigation')).classes,[]);});
 await check('Recipe shortcuts belong only to the enrolled class',async()=>{const a=await api(h.ids.customer,'dashboard'),b=await api(h.ids.stranger,'dashboard');assert.deepEqual(a.classes[0].recipe_shortcut,{id:recipe.id,title:'Approved student recipe'});assert.equal(b.classes[0].recipe_shortcut.id,foreign.id);assert.ok(!JSON.stringify(a.classes).includes(foreign.id));});
 await check('Question and submission context reject foreign modules and recipes',async()=>{for(const action of ['start_thread','draft_submission'])for(const context of [{recipe_id:foreign.id},{module_id:module.id}])await assert.rejects(api(h.ids.customer,action,{class_id:cookie.id,title:'Context test',subject:'Context test',body:'Question',visibility:'gallery',...context}));});
 const q=await api(h.ids.customer,'start_thread',{class_id:cookie.id,subject:'A recipe question',body:'Please help',type:'question',recipe_id:recipe.id});await api(h.ids.customer,'send_message',{id:q.id});
 await check('Needs reply reflects the latest sender rather than unread state',async()=>{await api(h.ids.staff,'read_thread',{id:q.thread_id,message_id:q.id});const inbox=await api(h.ids.staff,'threads',{filter:'needs_reply'});assert.equal(inbox.length,1);assert.equal(inbox[0].unread,0);assert.equal(inbox[0].needs_reply,true);assert.equal(inbox[0].account_name,'Alice Baker');assert.equal(inbox[0].recipe_title,'Approved student recipe');assert.ok(!JSON.stringify(inbox).includes('customer@example.test'));});
 await check('Instructor filters remain limited to assigned classes',async()=>{assert.deepEqual(await api(h.ids.teacher2,'threads',{filter:'all'}),[]);assert.deepEqual(await api(h.ids.staff,'threads',{class_id:cupcake.id}),[]);assert.deepEqual(await api(h.ids.stranger,'threads',{filter:'needs_reply'}),[]);});
 const reply=await api(h.ids.staff,'draft_reply',{id:q.thread_id,body:'Use room-temperature ingredients'});await api(h.ids.staff,'send_message',{id:reply.id});
 await check('A teacher reply clears Needs reply and creates an authorized dashboard shortcut',async()=>{assert.deepEqual(await api(h.ids.staff,'threads',{filter:'needs_reply'}),[]);const card=(await api(h.ids.customer,'dashboard')).classes[0];assert.equal(card.reply_thread_id,q.thread_id);assert.equal(card.unread,1);assert.equal((await api(h.ids.stranger,'dashboard')).classes[0].reply_thread_id,null);});
 const unsent=await api(h.ids.staff,'draft_reply',{id:q.thread_id,body:'UNSENT private draft'});
 await check('Reply polling returns the last submitted message without marking it read',async()=>{const status=await api(h.ids.customer,'thread_status',{id:q.thread_id});assert.equal(status.last_message_id,reply.id);assert.notEqual(status.last_message_id,unsent.id);assert.equal((await api(h.ids.customer,'threads'))[0].unread,1);});
 await check('Rendered-message read boundaries clear only the matching dashboard shortcut',async()=>{await api(h.ids.customer,'read_thread',{id:q.thread_id,message_id:reply.id});assert.equal((await api(h.ids.customer,'dashboard')).classes[0].reply_thread_id,null);});
 await check('Resolved and All filters remain distinct',async()=>{await api(h.ids.staff,'resolve_thread',{id:q.thread_id,resolved:true});assert.equal((await api(h.ids.staff,'threads',{filter:'resolved'})).length,1);assert.equal((await api(h.ids.staff,'threads',{filter:'all'})).length,1);assert.equal((await api(h.ids.staff,'threads',{filter:'needs_reply'})).length,0);await assert.rejects(api(h.ids.staff,'threads',{filter:'invalid'}));});
 const approved=await api(h.ids.customer,'draft_submission',{class_id:cookie.id,title:'Academy gallery bake',caption:'Public to signed-in Academy members',category:'Cookies',visibility:'gallery',show_name:false,recipe_id:recipe.id});await s.upload(h.ids.customer,{purpose:'submission',submission_id:approved.id});await api(h.ids.customer,'submit_work',{id:approved.id});await api(h.ids.staff,'moderate',{id:approved.id,status:'approved'});
 await check('Direct gallery routes expose approved posts to signed-in zero-class accounts',async()=>{const post=await api(h.ids.unverified,'gallery_post',{id:approved.id});assert.equal(post.title,'Academy gallery bake');assert.equal(post.display_name,'Academy member');assert.equal(post.recipe_title,'Approved student recipe');assert.equal(post.media.length,1);assert.ok(!JSON.stringify(post).includes('customer@example.test'));assert.ok(!JSON.stringify(post.media).includes('path'));});
 await check('Direct gallery routes deny every unapproved moderation state',async()=>{for(const state of ['pending','hidden','archived','removed']){await db.query('update tlb.academy_submissions set moderation=$1 where id=$2',[state,approved.id]);for(const actor of [h.ids.customer,h.ids.staff,h.ids.owner,h.ids.unverified])await assert.rejects(api(actor,'gallery_post',{id:approved.id}));}await db.query("update tlb.academy_submissions set moderation='approved' where id=$1",[approved.id]);});
 await check('Private instructor submissions never resolve as gallery routes, including for owners',async()=>{const p=await api(h.ids.customer,'draft_submission',{class_id:cookie.id,title:'Private test',visibility:'instructor'});await s.upload(h.ids.customer,{purpose:'submission',submission_id:p.id});await api(h.ids.customer,'submit_work',{id:p.id});for(const actor of [h.ids.customer,h.ids.staff,h.ids.owner,h.ids.unverified])await assert.rejects(api(actor,'gallery_post',{id:p.id}));});
 await check('Database relationships also reject foreign class context',async()=>{for(const table of ['academy_submissions','academy_message_threads']){const id=table==='academy_submissions'?approved.id:q.thread_id;await assert.rejects(db.query(`update tlb.${table} set module_id=$1 where id=$2`,[module.id,id]));await assert.rejects(db.query(`update tlb.${table} set recipe_id=$1 where id=$2`,[foreign.id,id]));}assert.equal((await api(h.ids.unverified,'gallery_post',{id:approved.id})).recipe_title,'Approved student recipe');});
 await check('Internal UX helpers cannot be called directly by browser roles',async()=>{await assert.rejects(h.as(h.ids.customer,()=>db.query("select tlb.academy_ux_read('navigation','{}')")));});
 await check('Revocation immediately removes navigation, shortcuts, threads and reply polling',async()=>{const a=await api(h.ids.owner,'account',{id:h.ids.customer});await api(h.ids.owner,'revoke',{id:a.enrollments.find(e=>e.class_id===cookie.id&&e.status==='active').id});assert.deepEqual((await api(h.ids.customer,'navigation')).classes,[]);assert.deepEqual((await api(h.ids.customer,'dashboard')).classes,[]);assert.deepEqual(await api(h.ids.customer,'threads'),[]);await assert.rejects(api(h.ids.customer,'thread_status',{id:q.thread_id}));assert.equal((await api(h.ids.customer,'gallery_post',{id:approved.id})).id,approved.id);});
}catch(error){results.push({name:'Approved UX database',status:'ISSUE REMAINS',error:error.message});console.error(error);process.exitCode=1;}
finally{await mkdir('tests/artifacts/academy-portal',{recursive:true});await writeFile('tests/artifacts/academy-portal/ux-database-results.json',JSON.stringify({results},null,2));await db.close();console.log(JSON.stringify({passed:results.filter(r=>r.status==='PASS').length,failed:results.filter(r=>r.status!=='PASS').length}));}
