import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdir,writeFile} from 'node:fs/promises';
import {setup} from './academy-portal.mjs';

// These are synthetic identities and documents. No production data or email
// provider is used. Assertions exercise the actual migrations and RPCs.
const {db,h,api,service,cookie,cupcake,upload,storage}=await setup();
const results=[];
const check=async(name,run)=>{try{await run();results.push({name,status:'PASS'});console.log('PASS',name);}catch(e){results.push({name,status:'ISSUE REMAINS',error:e.message});console.log('FAIL',name,e.message);}};
const denied=async(run)=>assert.rejects(run, e=>['42501','P0001','23503','23514','22023','22P02'].includes(e.code));
const createUser=async(name)=>{const id=randomUUID();await db.query("insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data) values($1,$2,now(),$3::jsonb)",[id,name+'@example.test',JSON.stringify({full_name:name,phone:'09170000000'})]);return id;};
const zero=await createUser('Zero Class'),onlyInstructor=await createUser('Instructor Only');
const roles={anonymous:null,zero,studentA:h.ids.customer,studentB:h.ids.stranger,instructorA:h.ids.staff,instructorB:h.ids.teacher2,owner:h.ids.owner};
const moduleA=await api(h.ids.owner,'save_module',{class_id:cookie.id,name:'Cookies'}),moduleB=await api(h.ids.owner,'save_module',{class_id:cupcake.id,name:'Cupcakes'});
const recipeA=await api(h.ids.owner,'save_recipe',{title:'Audit Cookie',document:{description:'Only approved student content',student_notes:'Teaching note',student_tips:'Teaching tip',variants:[{name:'Dough',groups:[{name:'Dry',ingredients:[{name:'Flour',quantity:'100',unit:'g',price:50,supplier:'SECRET'}]}],methods:[{name:'Mix',steps:[{instruction:'Mix gently',private_notes:'SECRET'}]}]}]}});
const recipeB=await api(h.ids.owner,'save_recipe',{title:'Audit Cupcake',document:{variants:[]}});
await api(h.ids.owner,'assign_recipe',{class_id:cookie.id,recipe_id:recipeA.id,module_id:moduleA.id});
await api(h.ids.owner,'assign_recipe',{class_id:cupcake.id,recipe_id:recipeB.id,module_id:moduleB.id});
const draft=async(visibility='gallery',user=h.ids.customer,classId=cookie.id,extra={})=>api(user,'draft_submission',{class_id:classId,title:'Audit creation',caption:'Emoji 🍪 <b>literal</b>',visibility,...extra});
const question=async(extra={})=>api(h.ids.customer,'start_thread',{class_id:cookie.id,subject:'Baking question',body:'How brown should the edge be? 🍪',type:'question',...extra});
const submit=async(visibility='gallery')=>{const s=await draft(visibility);const m=await upload(h.ids.customer,{purpose:'submission',submission_id:s.id});await api(h.ids.customer,'submit_work',{id:s.id});return {s,m};};

try{
 await check('Owner analytics returns class totals and recent audit activity',async()=>{const result=await api(h.ids.owner,'analytics');assert.equal(result.classes.length,2);assert.ok(result.audit.length>0);assert.ok(result.audit.every(row=>typeof row.actor_name==='string'));});
 for(const [role,user] of Object.entries(roles)){
  const permitted=['studentA','instructorA','owner'].includes(role);
  await check(`Class A authorization: ${role}`,async()=>{if(permitted)assert.equal((await api(user,'class',{id:cookie.id})).id,cookie.id);else await denied(()=>api(user,'class',{id:cookie.id}));});
  await check(`Recipe A authorization: ${role}`,async()=>{if(permitted){const r=await api(user,'recipe',{class_id:cookie.id,id:recipeA.id});assert.equal(r.id,recipeA.id);assert.ok(!JSON.stringify(r).includes('SECRET'));}else await denied(()=>api(user,'recipe',{class_id:cookie.id,id:recipeA.id}));});
  await check(`Private tables cannot be queried directly: ${role}`,async()=>{for(const table of ['academy_curricula','academy_enrollments','academy_student_recipes','academy_messages','academy_portal_media','academy_newsletter_preferences','recipes','recipe_versions','recipe_supplier_items','orders','payments'])await denied(()=>h.as(user,()=>db.query(`select * from tlb.${table} limit 1`)));});
 }
 for(const action of ['assign','revoke','save_instructor','save_class','save_recipe','import_recipe','production_recipes','accounts','account','analytics','broadcast_preview','broadcast_send','admin_media'])await check(`Student cannot call privileged action ${action}`,()=>denied(()=>api(h.ids.customer,action,{class_id:cookie.id,id:recipeA.id,user_ids:[h.ids.customer],version_id:randomUUID(),kind:'operational',audience:'students',subject:'test',body:'test',idempotency_key:randomUUID()})));
 await check('Cross-class module and recipe references rejected on student writes',async()=>{for(const relation of [{module_id:moduleB.id},{recipe_id:recipeB.id}]){await denied(()=>question(relation));await denied(()=>draft('gallery',h.ids.customer,cookie.id,relation));}});
 await check('Anonymous and zero-class accounts cannot start messages or submissions',async()=>{for(const user of [null,zero]){await denied(()=>api(user,'start_thread',{class_id:cookie.id,subject:'Test',body:'Test'}));await denied(()=>draft('gallery',user));}});
 await check('Instructor capability can be granted without order/payment staff access',async()=>{await api(h.ids.owner,'save_instructor',{id:onlyInstructor,display_name:'Independent Instructor'});assert.equal((await api(onlyInstructor,'admin_bootstrap')).owner,false);await denied(()=>h.api('admin_bootstrap',{},onlyInstructor));await denied(()=>h.as(onlyInstructor,()=>db.query("select public.recipe_api('bootstrap','{}')")));assert.equal((await db.query('select count(*) n from tlb.staff where user_id=$1',[onlyInstructor])).rows[0].n,0);});
 await check('Module ordering persists',async()=>{const second=await api(h.ids.owner,'save_module',{class_id:cookie.id,name:'Brownies'});await api(h.ids.owner,'reorder_modules',{class_id:cookie.id,ids:[second.id,moduleA.id]});assert.deepEqual((await api(h.ids.customer,'class',{id:cookie.id})).modules.map(m=>m.id),[second.id,moduleA.id]);});
 await check('Module reordering rejects foreign, duplicate and incomplete lists',async()=>{for(const ids of [[moduleB.id],[moduleA.id,moduleA.id],[]])await denied(()=>api(h.ids.owner,'reorder_modules',{class_id:cookie.id,ids}));});
 await check('Account search trims spaces and matches case-insensitive name/email/phone',async()=>{for(const query of [' ALICE ','CUSTOMER@EXAMPLE.TEST',' 09170000000 '])assert.ok((await api(h.ids.owner,'accounts',{query})).length>0,query);assert.deepEqual(await api(h.ids.owner,'accounts',{query:'no-such-account'}),[]);});
 await check('Duplicate assignment is idempotent and preserves history after removal',async()=>{const r=await api(h.ids.owner,'assign',{class_id:cookie.id,user_ids:[zero,zero]});assert.equal(r.assigned,1);assert.equal((await api(h.ids.owner,'assign',{class_id:cookie.id,user_ids:[zero]})).assigned,0);const a=await api(h.ids.owner,'account',{id:zero});await api(h.ids.owner,'revoke',{id:a.enrollments[0].id});assert.equal((await api(h.ids.owner,'assign',{class_id:cookie.id,user_ids:[zero]})).assigned,1);const a2=await api(h.ids.owner,'account',{id:zero});assert.equal(a2.enrollments.length,2);await api(h.ids.owner,'revoke',{id:a2.enrollments.find(e=>e.status==='active').id});});
 await check('Inactive and invalid class assignments rejected',async()=>{for(const status of ['draft','hidden','archived']){const c=await api(h.ids.owner,'save_class',{name:'Audit '+status,status});await denied(()=>api(h.ids.owner,'assign',{class_id:c.id,user_ids:[zero]}));}await denied(()=>api(h.ids.owner,'assign',{class_id:randomUUID(),user_ids:[zero]}));});

 const unpublished=await draft('instructor');
 await check('Unsubmitted private draft is not exposed to instructor',()=>denied(()=>api(h.ids.staff,'submission',{id:unpublished.id})));
 const qDraft=await question({subject:'UNSENT SUBJECT'});
 await check('Unsent question subject is absent from instructor inbox',async()=>assert.ok(!(await api(h.ids.staff,'threads')).some(t=>t.id===qDraft.thread_id)));
 const pub=await submit(),priv=await submit('instructor');
 for(const [role,user] of Object.entries(roles)){
  await check(`Pending gallery and private submission media: ${role}`,async()=>{const allowed=['studentA','instructorA','owner'].includes(role);for(const m of [pub.m,priv.m])assert.equal((await storage(user,m.path)).length,allowed?1:0);});
 }
 for(const moderation of ['approved','hidden','approved','archived','approved','removed']){
  await api(h.ids.staff,'moderate',{id:pub.s.id,status:moderation});
  for(const [role,user] of Object.entries(roles))await check(`Gallery ${moderation} media visibility: ${role}`,async()=>{const g=user?await api(user,'gallery'):null;if(user)assert.equal(g.posts.some(p=>p.id===pub.s.id),moderation==='approved');const privileged=['instructorA','owner'].includes(role);const own=role==='studentA'&&moderation!=='removed';const allowed=!!user&&(moderation==='approved'||privileged||own);assert.equal((await storage(user,pub.m.path)).length,allowed?1:0);});
 }
 await api(h.ids.staff,'moderate',{id:pub.s.id,status:'approved'});
 await check('Gallery payload omits customer contact, identity and order fields',async()=>{const p=(await api(zero,'gallery')).posts.find(p=>p.id===pub.s.id);for(const key of ['email','phone','address','user_id','orders','account_id'])assert.equal(p[key],undefined);assert.equal(p.display_name,'Alice B.');});
 await check('Private submissions cannot be made public even by moderation',()=>denied(()=>api(h.ids.owner,'moderate',{id:priv.s.id,status:'approved'})));
 await check('A forged upload cannot inject unrelated recipe associations',()=>denied(()=>api(h.ids.customer,'reserve_media',{purpose:'submission',submission_id:unpublished.id,recipe_id:recipeB.id,size_bytes:40,width:1,height:1})));
 await check('Upload count, size and dimensions validated on server',async()=>{const s=await draft();for(let i=0;i<8;i++)await api(h.ids.customer,'reserve_media',{purpose:'submission',submission_id:s.id,size_bytes:10,width:1,height:1});await denied(()=>api(h.ids.customer,'reserve_media',{purpose:'submission',submission_id:s.id,size_bytes:10,width:1,height:1}));const s2=await draft();for(const p of [{size_bytes:5242881,width:1,height:1},{size_bytes:10,width:4097,height:1},{size_bytes:0,width:1,height:1}])await denied(()=>api(h.ids.customer,'reserve_media',{purpose:'submission',submission_id:s2.id,...p}));});
 await check('Missing photos and unfinished uploads block submission',async()=>{const s=await draft();await denied(()=>api(h.ids.customer,'submit_work',{id:s.id}));const pending=await api(h.ids.customer,'reserve_media',{purpose:'submission',submission_id:s.id,size_bytes:10,width:1,height:1});await upload(h.ids.customer,{purpose:'submission',submission_id:s.id});await denied(()=>api(h.ids.customer,'submit_work',{id:s.id}));await api(h.ids.customer,'cancel_media',{id:pending.id});assert.equal((await api(h.ids.customer,'submit_work',{id:s.id})).submitted,true);});
 await check('Submission replay with same idempotency key creates one draft',async()=>{const key=randomUUID();const a=await draft('gallery',h.ids.customer,cookie.id,{idempotency_key:key});const b=await draft('gallery',h.ids.customer,cookie.id,{idempotency_key:key});assert.equal(a.id,b.id);});
 await check('Question and reply replay with same idempotency key create one message',async()=>{const key=randomUUID();const a=await question({idempotency_key:key}),b=await question({idempotency_key:key});assert.equal(a.id,b.id);await api(h.ids.customer,'send_message',{id:a.id});const rkey=randomUUID(),p={id:a.thread_id,body:'reply',idempotency_key:rkey};assert.equal((await api(h.ids.staff,'draft_reply',p)).id,(await api(h.ids.staff,'draft_reply',p)).id);});
 await check('Text validation rejects blank, overlong and invalid context requests',async()=>{for(const p of [{subject:' '},{subject:'x'.repeat(161)},{body:''},{body:'x'.repeat(10001)}])await denied(()=>question(p));await denied(()=>draft('gallery',h.ids.customer,cookie.id,{caption:'x'.repeat(5001)}));await denied(()=>draft('invalid'));});
 await check('Sent message retry creates one notification',async()=>{const q=await question();await api(h.ids.customer,'send_message',{id:q.id});await api(h.ids.customer,'send_message',{id:q.id});assert.equal(Number((await db.query("select count(*) n from tlb.outbox where payload->>'target_id'=$1",[q.id])).rows[0].n),1);});
 await check('Read markers are per participant and per thread',async()=>{const qa=await question(),qb=await question();for(const q of [qa,qb]){await api(h.ids.customer,'send_message',{id:q.id});assert.equal((await api(h.ids.customer,'threads')).find(t=>t.id===q.thread_id).unread,0);const r=await api(h.ids.staff,'draft_reply',{id:q.thread_id,body:'Teacher reply'});await api(h.ids.staff,'send_message',{id:r.id});}assert.equal((await api(h.ids.customer,'threads')).find(t=>t.id===qa.thread_id).unread,1);await api(h.ids.customer,'thread',{id:qa.thread_id});const list=await api(h.ids.customer,'threads');assert.equal(list.find(t=>t.id===qa.thread_id).unread,0);assert.equal(list.find(t=>t.id===qb.thread_id).unread,1);});
 await check('Instructor reassignment preserves submitted history and denies old teacher',async()=>{const q=await question();await api(h.ids.customer,'send_message',{id:q.id});let c=(await api(h.ids.owner,'admin_bootstrap')).classes.find(x=>x.id===cookie.id);await api(h.ids.owner,'save_class',{...c,instructor_id:h.ids.teacher2});await denied(()=>api(h.ids.staff,'thread',{id:q.thread_id}));assert.equal((await api(h.ids.teacher2,'thread',{id:q.thread_id})).messages.length,1);c=(await api(h.ids.owner,'admin_bootstrap')).classes.find(x=>x.id===cookie.id);await api(h.ids.owner,'save_class',{...c,instructor_id:h.ids.staff});});
 await check('Inactive instructor cannot read or start new instructor work',async()=>{await api(h.ids.owner,'save_instructor',{id:h.ids.staff,display_name:'Chef Cookie',active:false});await denied(()=>api(h.ids.staff,'admin_bootstrap'));await denied(()=>question());await api(h.ids.owner,'save_instructor',{id:h.ids.staff,display_name:'Chef Cookie',active:true});});
 await check('Disabled instructor also blocks pending student message send',async()=>{const q=await question();await api(h.ids.owner,'save_instructor',{id:h.ids.staff,display_name:'Chef Cookie',active:false});try{await denied(()=>api(h.ids.customer,'send_message',{id:q.id}));}finally{await api(h.ids.owner,'save_instructor',{id:h.ids.staff,display_name:'Chef Cookie',active:true});}});
 for(const type of ['announcement','upcoming']){
  const save=type==='announcement'?'save_announcement':'save_upcoming';
  await check(`${type} draft/published/hidden/archived and invalid URL validation`,async()=>{for(const status of ['draft','published','hidden','archived']){const r=await api(h.ids.owner,save,{title:'Audit '+status,status});const d=await api(zero,'dashboard');assert.equal(d[type==='announcement'?'announcements':'upcoming'].some(x=>x.id===r.id),status==='published');}for(const url of ['javascript:alert(1)','//evil.test','https://ok.test/<script>'])await denied(()=>api(h.ids.owner,save,{title:'Bad CTA',status:'published',[type==='announcement'?'cta_url':'inquiry_url']:url}));});
  await check(`${type} blank title rejected`,()=>denied(()=>api(h.ids.owner,save,{title:' ',status:'published'})));
 }
 await check('Announcement read status persists independently',async()=>{const a=await api(h.ids.owner,'save_announcement',{title:'Read test',status:'published'});await api(h.ids.customer,'announcement',{id:a.id});assert.equal((await api(h.ids.customer,'dashboard')).announcements.find(x=>x.id===a.id).read,true);assert.equal((await api(h.ids.stranger,'dashboard')).announcements.find(x=>x.id===a.id).read,false);});
 await check('Academy/Kitchen newsletter four combinations stay independent',async()=>{await db.query("insert into tlb.newsletter_subscribers(email,status) values('customer@example.test','unsubscribed') on conflict(email) do update set status='unsubscribed'");for(const academy of [false,true])for(const kitchen of ['unsubscribed','subscribed']){await db.query("update tlb.newsletter_subscribers set status=$1 where email='customer@example.test'",[kitchen]);await api(h.ids.customer,'newsletter',{academy});const a=await api(h.ids.owner,'account',{id:h.ids.customer});assert.equal(a.academy_newsletter,academy);assert.equal(a.kitchen_newsletter,kitchen);}});
 await check('Marketing segments respect Academy consent, operational segments do not alter consent',async()=>{await api(h.ids.customer,'newsletter',{academy:true});await api(h.ids.stranger,'newsletter',{academy:false});const p={subject:'Notice',body:'Class notice',kind:'marketing'};for(const audience of ['students','class','instructor','selected','subscribers']){const r=await api(h.ids.owner,'broadcast_preview',{...p,audience,class_id:cookie.id,instructor_id:h.ids.staff,emails:['customer@example.test','stranger@example.test']});assert.equal(r.recipients,1);}assert.equal((await api(h.ids.owner,'broadcast_preview',{...p,kind:'operational',audience:'students'})).recipients,2);});
 await check('Broadcast replay is idempotent and missing idempotency key is rejected',async()=>{const p={subject:'Class notice',body:'Only synthetic recipients',kind:'operational',audience:'students',idempotency_key:randomUUID()};const a=await api(h.ids.owner,'broadcast_send',p),b=await api(h.ids.owner,'broadcast_send',p);assert.equal(a.id,b.id);delete p.idempotency_key;await denied(()=>api(h.ids.owner,'broadcast_send',p));});
 await check('Academy notification payload routes to assigned teacher with no media URLs',async()=>{const q=await question();await api(h.ids.customer,'send_message',{id:q.id});const e=(await db.query("select to_email,payload from tlb.outbox where payload->>'target_id'=$1",[q.id])).rows[0];assert.equal(e.to_email,'staff@example.test');assert.equal(e.payload.class_id,cookie.id);assert.equal(e.payload.recipient_id,h.ids.staff);assert.ok(!JSON.stringify(e.payload).includes('.webp'));});
 await check('Private submission notification links to submissions rather than empty inbox',async()=>{const {s}=await submit('instructor');const e=(await db.query("select payload from tlb.outbox where payload->>'target_id'=$1",[s.id])).rows[0];assert.ok(e.payload.url.includes('#submissions'));});
 await check('Enrollment removal denies old class, recipes, private media and messaging',async()=>{const q=await question();await api(h.ids.customer,'send_message',{id:q.id});const a=await api(h.ids.owner,'account',{id:h.ids.customer});await api(h.ids.owner,'revoke',{id:a.enrollments.find(e=>e.class_id===cookie.id&&e.status==='active').id});for(const [action,p] of [['class',{id:cookie.id}],['recipe',{id:recipeA.id,class_id:cookie.id}],['thread',{id:q.thread_id}],['draft_reply',{id:q.thread_id,body:'try'}],['draft_submission',{class_id:cookie.id,title:'Try',visibility:'gallery'}]])await denied(()=>api(h.ids.customer,action,p));assert.equal((await storage(h.ids.customer,priv.m.path)).length,0);assert.ok((await api(h.ids.customer,'gallery')).posts.some(p=>p.id===pub.s.id));});
}finally{await mkdir('work/academy-audit',{recursive:true});const report={scope:'isolated real migrations and RPC/RLS, synthetic data, no provider delivery',results,passed:results.filter(r=>r.status==='PASS').length,failed:results.filter(r=>r.status!=='PASS').length};await writeFile('work/academy-audit/database-matrix.json',JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,failed:report.failed}));await db.close();if(report.failed)process.exitCode=1;}
