import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {auditHarness} from './academy-audit-harness.mjs';
const s=await auditHarness(),{h,api,db,cookie,cupcake,origin,out}=s,results=[];
const check=async(name,fn)=>{try{await fn();results.push({name,status:'PASS'});console.log('PASS',name);}catch(e){results.push({name,status:'ISSUE REMAINS',error:e.message});console.log('FAIL',name,e.message.split('\n')[0]);}};
const open=async(user,path='',width=1440)=>{const p=await s.pageFor(user,width);await p.page.goto(origin+'/academy/dashboard'+path);await p.page.waitForFunction(()=>document.querySelector('.ap-main,.ap-login'));return p;};
const recipe=await api(h.ids.owner,'save_recipe',{title:'Audit Baking Recipe',document:{description:'Tablet recipe audit',student_notes:'Let the cake cool',variants:[{name:'Main',yield:{quantity:'12',unit:'cookies'},groups:[{name:'Ingredients',ingredients:[{name:'All-purpose flour',quantity:'250',unit:'g'}]}],methods:[{name:'Prepare',steps:[{instruction:'Mix the ingredients gently.',temperature:'180 C',timer_minutes:'15'}]}],equipment:['Mixing bowl']}]}});
await api(h.ids.owner,'assign_recipe',{class_id:cookie.id,recipe_id:recipe.id});
let png;
try{
 const prep=await open(h.ids.customer);png=Buffer.from(await prep.page.evaluate(()=>{const c=document.createElement('canvas');c.width=160;c.height=100;const x=c.getContext('2d');x.fillStyle='#bc8755';x.fillRect(0,0,160,100);return c.toDataURL('image/png').split(',')[1];}),'base64');await prep.context.close();
 await check('An in-flight private class response cannot reappear after logout',async()=>{const p=await open(h.ids.customer,'#classes');const d=p.delayNext('class');await p.page.getByRole('link',{name:'View class →',exact:true}).click();await d.pending;await p.page.evaluate(()=>window.auditChangeSession(null));await p.page.getByRole('heading',{name:'Welcome to TLB Academy'}).waitFor();d.release();await p.page.waitForTimeout(150);assert.ok(await p.page.getByRole('heading',{name:'Welcome to TLB Academy'}).isVisible());assert.equal(await p.page.getByRole('heading',{name:'Cookies & Brownies',exact:true}).count(),0);await p.context.close();});
 await check('Older class request cannot overwrite a newer navigation destination',async()=>{const p=await open(h.ids.customer,'#classes');const d=p.delayNext('class');await p.page.getByRole('link',{name:'View class →',exact:true}).click();await d.pending;await p.page.evaluate(()=>location.hash='gallery');await p.page.getByRole('heading',{name:'What our students are baking'}).waitFor();d.release();await p.page.waitForTimeout(150);assert.ok(await p.page.getByRole('heading',{name:'What our students are baking'}).isVisible());await p.context.close();});
 await check('Question upload failure can be retried without losing the message',async()=>{const p=await open(h.ids.customer,'#ask/'+cookie.id,390);await p.page.getByLabel('Subject',{exact:true}).fill('Retry question');await p.page.getByLabel('Message',{exact:true}).fill('Please help with this cake.');await p.page.locator('input[name=photos]').setInputFiles({name:'cake.png',mimeType:'image/png',buffer:png});p.failUpload(1);await p.page.getByRole('button',{name:'Send private message'}).click();await p.page.getByRole('button',{name:'Retry upload & send'}).click();await p.page.waitForFunction(()=>location.hash.startsWith('#thread/'));await p.page.getByText('Please help with this cake.',{exact:true}).waitFor();await p.context.close();});
 await check('Lost draft response can be retried without duplicate submissions',async()=>{const p=await open(h.ids.customer,'#share/'+cookie.id);await p.page.getByLabel('Product / title').fill('Lost draft response');await p.page.locator('input[name=photos]').setInputFiles({name:'cake.png',mimeType:'image/png',buffer:png});p.failNext('draft_submission','after');await p.page.getByRole('button',{name:'Submit your creation'}).click();await p.page.getByRole('alert').waitFor();await p.page.getByRole('button',{name:'Submit your creation'}).click();await p.page.waitForFunction(()=>location.hash.startsWith('#class/'));assert.equal(Number((await db.query("select count(*) n from tlb.academy_submissions where title='Lost draft response'")).rows[0].n),1);await p.context.close();});
 await check('Focusing an open thread does not mark unseen replies read without rendering them',async()=>{const q=await api(h.ids.customer,'start_thread',{class_id:cookie.id,subject:'Focus test',body:'Initial question',type:'question'});await api(h.ids.customer,'send_message',{id:q.id});const p=await open(h.ids.customer,'#thread/'+q.thread_id);await p.page.getByText('Initial question',{exact:true}).waitFor();const reply=await api(h.ids.staff,'draft_reply',{id:q.thread_id,body:'New teacher reply after focus'});await api(h.ids.staff,'send_message',{id:reply.id});await p.page.evaluate(()=>window.dispatchEvent(new Event('focus')));await p.page.waitForTimeout(250);const rendered=await p.page.getByText('New teacher reply after focus',{exact:true}).isVisible();const unread=(await api(h.ids.customer,'threads')).find(t=>t.id===q.thread_id).unread;assert.ok(rendered||unread>0,'Reply is neither displayed nor unread');await p.context.close();});
 await check('Malformed route gives a human-readable error without SQL details',async()=>{const p=await open(h.ids.customer,'#recipe/not-a-uuid/not-a-uuid');await p.page.getByRole('button',{name:'Try again'}).waitFor();const body=await p.page.locator('body').innerText();assert.ok(!/invalid input syntax|uuid|sql|relation|constraint|PGRST/i.test(body));await p.context.close();});
 await check('Admin thumbnail upload retry does not duplicate the newly saved class',async()=>{const p=await s.pageFor(h.ids.owner);await p.page.goto(origin+'/academy/admin#classes/new');await p.page.getByLabel('Class name',{exact:true}).fill('Admin upload retry');await p.page.getByLabel('Primary instructor').selectOption(h.ids.staff);await p.page.getByLabel('Status',{exact:true}).selectOption('active');await p.page.locator('input[name=photo]').setInputFiles({name:'class.png',mimeType:'image/png',buffer:png});p.failUpload(1);await p.page.getByRole('button',{name:'Save changes',exact:true}).click();await p.page.getByRole('button',{name:'Retry upload & send'}).click();await p.page.getByRole('button',{name:'Add module'}).waitFor();assert.equal(Number((await db.query("select count(*) n from tlb.academy_curricula where name='Admin upload retry'")).rows[0].n),1);await p.context.close();});
 await check('Gallery filter failure can retry the same page without skipping results',async()=>{const p=await open(h.ids.customer,'#gallery');p.failNext('gallery','before');await p.page.getByLabel('Filter by category').selectOption('Cookies');await p.page.getByRole('status').waitFor();assert.ok(await p.page.getByLabel('Filter by category').isEnabled());await p.page.getByLabel('Filter by category').selectOption('');await p.page.getByRole('heading',{name:'The gallery is warming up.'}).waitFor();await p.context.close();});
 await check('Gallery page retry and rapid filters preserve the correct result set',async()=>{for(let i=0;i<25;i++){const draft=await api(h.ids.customer,'draft_submission',{class_id:cookie.id,title:'Pagination cake '+i,visibility:'gallery',category:'Cakes'});await s.upload(h.ids.customer,{purpose:'submission',submission_id:draft.id});await api(h.ids.customer,'submit_work',{id:draft.id});await api(h.ids.owner,'moderate',{id:draft.id,status:'approved'});}const p=await open(h.ids.customer,'#gallery');await p.page.locator('[data-post]').first().waitFor();assert.equal(await p.page.locator('[data-post]').count(),24);p.failNext('gallery','before');await p.page.getByRole('button',{name:'Load more'}).click();await p.page.locator('#ap-notice').waitFor();await p.page.getByRole('button',{name:'Load more'}).click();await p.page.waitForFunction(()=>document.querySelectorAll('[data-post]').length===25);const delay=p.delayNext('gallery');await p.page.getByLabel('Filter by category').selectOption('Cookies');await delay.pending;await p.page.getByLabel('Filter by category').selectOption('Cakes');await p.page.waitForFunction(()=>document.querySelectorAll('[data-post]').length===24);delay.release();await p.page.waitForTimeout(150);assert.equal(await p.page.locator('[data-post]').count(),24);await p.context.close();});
 for(const width of [320,390,430,768,1024,1366,1920])await check(`Student routes fit viewport ${width}`,async()=>{const p=await s.pageFor(h.ids.customer,width);for(const route of ['', '#classes','#class/'+cookie.id,'#recipe/'+cookie.id+'/'+recipe.id,'#gallery','#announcements','#upcoming','#ask/'+cookie.id,'#share/'+cookie.id,'#messages','#preferences']){await p.page.goto(origin+'/academy/dashboard'+route);await p.page.waitForFunction(()=>document.querySelector('.ap-main'));await p.page.waitForTimeout(30);assert.ok(await p.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),route+' horizontal overflow');}await p.page.screenshot({path:join(out,'preferences-'+width+'.png'),fullPage:true});await p.context.close();});
 await check('Zero-class and logged-out layouts fit a small phone',async()=>{for(const user of [null,h.ids.unverified]){const p=await open(user,'',320);assert.ok(await p.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.page.screenshot({path:join(out,user?'zero-class-320.png':'logged-out-320.png'),fullPage:true});await p.context.close();}});
 await check('Recipe and private modal remain keyboard accessible',async()=>{const p=await open(h.ids.customer,'#recipe/'+cookie.id+'/'+recipe.id,768);await p.page.getByRole('button',{name:'Ingredients',exact:true}).focus();await p.page.keyboard.press('Enter');await p.page.getByRole('cell',{name:'250 g',exact:true}).waitFor();await p.page.keyboard.press('Tab');assert.equal(await p.page.evaluate(()=>document.activeElement.tagName),'BUTTON');await p.page.screenshot({path:join(out,'tablet-recipe.png'),fullPage:true});await p.context.close();});
}finally{await writeFile(join(out,'results.json'),JSON.stringify({results,errors:s.errors,scope:'Actual Academy pages and RPCs; synthetic Auth/storage transport; desktop Chrome or Edge with emulated viewports'},null,2));for(const c of s.browser.contexts())for(const p of c.pages())await p.screenshot({path:join(out,'failure-'+s.browser.contexts().indexOf(c)+'.png'),fullPage:true}).catch(()=>{});await s.close();console.log(JSON.stringify({passed:results.filter(r=>r.status==='PASS').length,failed:results.filter(r=>r.status!=='PASS').length}));if(results.some(r=>r.status!=='PASS'))process.exitCode=1;}
