import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {auditHarness} from './academy-audit-harness.mjs';
const s=await auditHarness(),{h,cookie,cupcake,origin}=s,results=[],out='work/academy-audit/approved-ux-'+(process.env.PLAYWRIGHT_CHANNEL||'chrome');await mkdir(out,{recursive:true});
const api=(actor,action,p={})=>s.serial(()=>s.api(actor,action,p));
const ready=page=>page.waitForFunction(()=>document.querySelector('#academy-app')?.getAttribute('aria-busy')==='false');
const open=async(actor,path='',width=1440)=>{const p=await s.pageFor(actor,width);await p.page.goto(origin+'/academy/dashboard'+path);await ready(p.page);return p;};
let n=0;const check=async(name,fn)=>{n++;try{await fn();results.push({name,status:'PASS'});console.log('PASS',name);}catch(error){results.push({name,status:'ISSUE REMAINS',error:error.message});console.log('FAIL',name,error.message.split('\n')[0]);for(const context of s.browser.contexts())for(const page of context.pages()){await page.screenshot({path:out+'/failure-'+n+'-'+s.browser.contexts().indexOf(context)+'.png',fullPage:true}).catch(()=>{});}}};
try{
 const prep=await open(h.ids.customer);const buffers=await prep.page.evaluate(()=>{const c=document.createElement('canvas');c.width=160;c.height=100;c.getContext('2d').fillRect(0,0,160,100);return {png:c.toDataURL('image/png').split(',')[1],webp:c.toDataURL('image/webp').split(',')[1]};});await prep.context.close();const png=Buffer.from(buffers.png,'base64'),webp=Buffer.from(buffers.webp,'base64');
 const recipe=await api(h.ids.owner,'save_recipe',{title:'UX Chocolate Chip Cookies',document:{description:'A soft-centred cookie.',student_notes:'Cool the tray before the next batch.',student_tips:'Bake one test cookie first.',variants:[{name:'Cookie dough',yield:{quantity:'12',unit:'cookies',pan_size:'30 cm tray'},groups:[{name:'Dry ingredients',ingredients:[{name:'All-purpose flour',quantity:'250',unit:'g',brand:'Teaching Brand'}]}],methods:[{name:'Make the dough',steps:[{instruction:'Fold gently until the flour disappears.',timer_minutes:'3',temperature:'22 C',equipment:'Spatula'},{instruction:'Bake until the edges turn golden.'}]}],equipment:['Mixing bowl','Spatula'],baking:[{name:'Oven',top:'175 C',bottom:'165 C',fan:'off',minutes:'15'}]}]}});await api(h.ids.owner,'assign_recipe',{class_id:cookie.id,recipe_id:recipe.id});
 const q=await api(h.ids.customer,'start_thread',{class_id:cookie.id,subject:'UX baking question',body:'How long should I chill this dough?',recipe_id:recipe.id,type:'question'});await api(h.ids.customer,'send_message',{id:q.id});const r=await api(h.ids.staff,'draft_reply',{id:q.thread_id,body:'Chill for 30 minutes.'});await api(h.ids.staff,'send_message',{id:r.id});
 const ann=await api(h.ids.owner,'save_announcement',{title:'UX unread announcement',summary:'Prepare for your next class.',content:'Set out your mixing bowl.',status:'published'});
 await api(h.ids.owner,'save_upcoming',{title:'UX Bread Workshop',schedule:'Saturday · 9:00 AM',description:'A morning of shaping and baking.',products:['Soft rolls','Braided loaf'],cta:'Ask about the workshop',inquiry_url:'https://thelittlebakerkitchen.com/contactus.html',status:'published'});
 const gallery=[];
 for(let i=0;i<28;i++){
  const actor=i<26?h.ids.customer:h.ids.stranger,cls=i<26?cookie.id:cupcake.id;
  const post=await api(actor,'draft_submission',{class_id:cls,title:'UX gallery bake '+i,caption:'Synthetic gallery caption '+i,category:i<26?'Cookies':'Cupcakes',visibility:'gallery',show_name:true});
  const media=await s.serial(()=>s.upload(actor,{purpose:'submission',submission_id:post.id}));s.mediaFiles.set(media.path,webp);
  if(i===25){const second=await s.serial(()=>s.upload(actor,{purpose:'submission',submission_id:post.id}));s.mediaFiles.set(second.path,webp);}
  await api(actor,'submit_work',{id:post.id});await api(h.ids.owner,'moderate',{id:post.id,status:'approved'});gallery.push(post);
 }
 await check('Dashboard puts real new replies and a permitted recipe shortcut before announcements',async()=>{
  const p=await open(h.ids.customer);const reply=p.page.getByRole('region',{name:'New instructor replies'});await reply.waitFor();assert.ok(await p.page.locator(`a[href="#recipe/${cookie.id}/${recipe.id}"]`).isVisible());
  const order=await p.page.evaluate(()=>({reply:document.querySelector('.ap-reply-summary').offsetTop,classes:document.querySelector('.ap-dashboard-classes').offsetTop,announcements:document.querySelector('.ap-announcement').offsetTop}));assert.ok(order.reply<order.classes&&order.classes<order.announcements);await p.context.close();
 });
 await check('Mobile navigation has four visible destinations and a keyboard-usable More menu',async()=>{
  const p=await open(h.ids.customer,'',390);assert.equal(await p.page.locator('.ap-mobile-nav>a').count(),4);assert.ok(await p.page.getByRole('link',{name:'Open class',exact:true}).evaluate(e=>e.getBoundingClientRect().bottom<844));
  const more=p.page.locator('.ap-more:visible>summary');await more.focus();await p.page.keyboard.press('Enter');await p.page.getByRole('link',{name:'Email preferences',exact:true}).waitFor();await p.page.keyboard.press('Escape');assert.equal(await p.page.locator('.ap-more:visible').getAttribute('open'),null);assert.equal(await more.evaluate(e=>e===document.activeElement),true);await p.page.screenshot({path:out+'/mobile-dashboard.png',fullPage:true});await p.context.close();
 });
 await check('Logged-out and zero-class accounts get clear discovery paths without class controls',async()=>{
  const guest=await open(null,'',390);await guest.page.getByRole('heading',{name:'Welcome to TLB Academy'}).waitFor();await guest.page.getByText('Your classes & recipes',{exact:true}).waitFor();assert.equal(await guest.page.locator('.ap-gate-benefits li').count(),3);await guest.context.close();
  const zero=await open(h.ids.unverified,'',390);for(const text of ['Student gallery','Upcoming classes','Announcements'])assert.ok(await zero.page.getByRole('link',{name:text,exact:true}).isVisible());assert.equal(await zero.page.getByRole('link',{name:'Open class',exact:true}).count(),0);await zero.context.close();
 });
 await check('Class materials precede sharing and general-contact support',async()=>{
  const p=await open(h.ids.customer,'#class/'+cookie.id);const positions=await p.page.evaluate(()=>({recipe:document.querySelector('.ap-recipe-link').getBoundingClientRect().top,support:document.querySelector('.ap-class-support').getBoundingClientRect().top}));assert.ok(positions.recipe<positions.support);await p.page.getByText('More class support',{exact:true}).click();assert.ok(await p.page.getByRole('link',{name:'Contact Instructor — Chef Cookie',exact:true}).isVisible());await p.context.close();
 });
 await check('Baking view exposes ingredients and method together and preserves all teaching fields',async()=>{
  const p=await open(h.ids.customer,'#recipe/'+cookie.id+'/'+recipe.id);await p.page.getByRole('cell',{name:'250 g',exact:true}).waitFor();await p.page.getByText('Fold gently until the flour disappears.',{exact:true}).waitFor();
  for(const text of ['Teaching Brand','30 cm tray','3 minutes','22 C','175 C','165 C','Cool the tray before the next batch.','Bake one test cookie first.'])assert.ok((await p.page.locator('.ap-recipe').innerText()).includes(text),text);
  const boxes=await p.page.evaluate(()=>({ingredients:document.querySelector('.ap-ingredients-panel').getBoundingClientRect().x,method:document.querySelector('.ap-method-panel').getBoundingClientRect().x}));assert.ok(boxes.method>boxes.ingredients+200);assert.equal(await p.page.getByRole('button',{name:/download|print|export/i}).count(),0);
  await p.page.getByRole('button',{name:'Method',exact:true}).focus();await p.page.keyboard.press('Enter');assert.equal(await p.page.evaluate(()=>document.activeElement.textContent),'Method');await p.page.screenshot({path:out+'/baking-desktop.png',fullPage:true});await p.context.close();
 });
 await check('Tablet recipe uses the full workspace and keeps section targets at least 44 pixels tall',async()=>{
  const p=await open(h.ids.customer,'#recipe/'+cookie.id+'/'+recipe.id,1024);assert.equal(await p.page.locator('.ap-sidebar').isVisible(),false);const widths=await p.page.evaluate(()=>({main:document.querySelector('.ap-main').getBoundingClientRect().width,targets:[...document.querySelectorAll('.ap-recipe-jumps button')].map(b=>b.getBoundingClientRect().height)}));assert.ok(widths.main>1000);assert.ok(widths.targets.every(v=>v>=44));await p.page.setViewportSize({width:820,height:1100});await p.page.locator('.ap-ingredients-panel>summary').click();assert.equal(await p.page.getByRole('cell',{name:'250 g',exact:true}).isVisible(),false);await p.page.getByRole('button',{name:'Ingredients',exact:true}).click();assert.ok(await p.page.getByRole('cell',{name:'250 g',exact:true}).isVisible());await p.context.close();
 });
 await check('Share previews allow individual removal while preserving the gallery default and private audience choice',async()=>{
  const p=await open(h.ids.customer,'#share/'+cookie.id,390);assert.ok(await p.page.getByRole('radio',{name:/Share to Academy Gallery/}).isChecked());await p.page.getByLabel('Product / title').fill('UX preview removal bake');
  await p.page.locator('input[name=photos]').setInputFiles([{name:'keep.png',mimeType:'image/png',buffer:png},{name:'remove.png',mimeType:'image/png',buffer:png}]);await p.page.waitForFunction(()=>document.querySelectorAll('.ap-photo-preview img').length===2);await p.page.getByRole('button',{name:'Remove photo 2: remove.png',exact:true}).click();assert.equal(await p.page.locator('.ap-photo-preview').count(),1);await p.page.getByRole('radio',{name:/Private to Instructor — Chef Cookie/}).check();await p.page.getByRole('button',{name:'Submit your creation'}).click();await p.page.waitForFunction(()=>location.hash.startsWith('#class/'));
  const rows=await s.serial(()=>s.db.query("select s.visibility,count(m.id)::int photos from tlb.academy_submissions s join tlb.academy_portal_media m on m.submission_id=s.id where s.title='UX preview removal bake' group by s.visibility"));assert.deepEqual(rows.rows,[{visibility:'instructor',photos:1}]);await p.context.close();
 });
 await check('Photo errors are associated with the picker and create no premature draft',async()=>{
  const p=await open(h.ids.customer,'#share/'+cookie.id);await p.page.getByLabel('Product / title').fill('UX invalid photo');await p.page.getByRole('button',{name:'Submit your creation'}).click();await p.page.getByRole('alert').waitFor();assert.equal(await p.page.locator('[name=photos]').getAttribute('aria-invalid'),'true');const id=await p.page.locator('[name=photos]').getAttribute('aria-describedby');assert.ok(await p.page.locator('#'+id).isVisible());assert.equal(p.calls.filter(c=>c.action==='draft_submission').length,0);await p.context.close();
 });
 await check('Asking from a recipe carries instructor, recipe and subject context into the submitted question',async()=>{
  const p=await open(h.ids.customer,'#recipe/'+cookie.id+'/'+recipe.id);await p.page.getByRole('link',{name:'Ask Chef Cookie',exact:true}).click();await p.page.getByLabel('Subject',{exact:true}).waitFor();assert.equal(await p.page.getByLabel('Subject',{exact:true}).inputValue(),'Question about UX Chocolate Chip Cookies');assert.equal(await p.page.getByLabel('Related recipe').inputValue(),recipe.id);await p.page.getByLabel('Message',{exact:true}).fill('UX contextual question');await p.page.getByRole('button',{name:'Send private message'}).click();await p.page.waitForFunction(()=>location.hash.startsWith('#thread/'));const thread=await api(h.ids.customer,'thread',{id:(await p.page.evaluate(()=>location.hash)).split('/')[1],mark_read:false});assert.equal(thread.recipe_id,recipe.id);await p.context.close();
 });
 await check('New replies load without scrolling older content or losing the draft; jumping marks them read',async()=>{
  const older=await api(h.ids.staff,'draft_reply',{id:q.thread_id,body:Array.from({length:35},(_,i)=>'Earlier baking note '+(i+1)+'.').join('\n')});await api(h.ids.staff,'send_message',{id:older.id});
  const p=await open(h.ids.customer,'#thread/'+q.thread_id);await p.page.getByLabel('Your reply',{exact:true}).fill('My draft reply stays here');await p.page.locator('input[name=photos]').setInputFiles({name:'reply.png',mimeType:'image/png',buffer:png});await p.page.locator('.ap-photo-preview img').waitFor();await p.page.evaluate(()=>scrollTo(0,0));
  const reply=await api(h.ids.staff,'draft_reply',{id:q.thread_id,body:'UX newly arrived reply'});await api(h.ids.staff,'send_message',{id:reply.id});await p.page.evaluate(()=>window.dispatchEvent(new Event('focus')));await p.page.getByRole('button',{name:'Show new reply'}).waitFor();assert.equal(await p.page.getByText('UX newly arrived reply',{exact:true}).count(),1);assert.equal(await p.page.evaluate(()=>scrollY),0);assert.equal((await api(h.ids.customer,'threads')).find(t=>t.id===q.thread_id).unread,1);
  await p.page.getByRole('button',{name:'Show new reply'}).click();await p.page.waitForFunction(()=>document.activeElement.matches('.ap-message'));await p.page.getByText('UX newly arrived reply',{exact:true}).waitFor();assert.equal(await p.page.getByLabel('Your reply',{exact:true}).inputValue(),'My draft reply stays here');assert.equal(await p.page.locator('.ap-photo-preview img').count(),1);assert.equal((await api(h.ids.customer,'threads')).find(t=>t.id===q.thread_id).unread,0);await p.context.close();
 });
 await check('Gallery browser Back keeps filters, loaded pages and position; multiple photos have navigation',async()=>{
  const p=await open(h.ids.customer,'#gallery',390);await p.page.getByLabel('Filter by category').selectOption('Cookies');await p.page.waitForFunction(()=>document.querySelectorAll('[data-post]').length===24&&document.querySelector('.ap-filter-chip'));
  await p.page.getByRole('button',{name:'Load more',exact:true}).click();await p.page.waitForFunction(()=>document.querySelectorAll('[data-post]').length===26);
  const post=p.page.locator(`[data-post="${gallery[25].id}"]`);await post.scrollIntoViewIfNeeded();const before=await p.page.evaluate(()=>scrollY);await post.click();await p.page.getByText('Photo 1 of 2',{exact:true}).waitFor();await p.page.getByRole('button',{name:'Next photo',exact:true}).click();await p.page.getByText('Photo 2 of 2',{exact:true}).waitFor();await p.page.goBack();await p.page.waitForFunction(()=>location.hash==='#gallery'&&!document.querySelector('dialog'));
  assert.equal(await p.page.getByLabel('Filter by category').inputValue(),'Cookies');assert.equal(await p.page.locator('[data-post]').count(),26);assert.ok(Math.abs(await p.page.evaluate(()=>scrollY)-before)<60);await p.page.getByRole('button',{name:'Clear all',exact:true}).click();await p.page.waitForFunction(()=>document.querySelectorAll('.ap-filter-chip').length===0);await p.context.close();
 });
 await check('Gallery state resumes after another view and is cleared on account change',async()=>{
  const p=await open(h.ids.customer,'#gallery');await p.page.getByLabel('Filter by category').selectOption('Cookies');await p.page.locator('.ap-filter-chip').waitFor();await p.page.evaluate(()=>location.hash='upcoming');await p.page.getByRole('heading',{name:'Coming up in the Academy'}).waitFor();await p.page.evaluate(()=>location.hash='gallery');await p.page.getByRole('heading',{name:'What our students are baking'}).waitFor();assert.equal(await p.page.getByLabel('Filter by category').inputValue(),'Cookies');await p.page.evaluate(id=>window.auditChangeSession(id),h.ids.unverified);await p.page.waitForFunction(()=>document.querySelector('#ap-gallery-category')?.value==='');await p.context.close();
 });
 await check('Direct gallery URL denies a private post without rendering its caption or image',async()=>{
  const privatePost=(await s.serial(()=>s.db.query("select id from tlb.academy_submissions where title='UX preview removal bake'"))).rows[0];const p=await open(h.ids.unverified,'#gallery/'+privatePost.id);await p.page.getByRole('heading',{name:'Academy is unavailable right now.'}).waitFor();assert.equal(await p.page.locator('[data-media-id]').count(),0);assert.ok(!(await p.page.locator('body').innerText()).includes('UX preview removal bake'));await p.context.close();
 });
 await check('Gallery downloads only nearby images until the user scrolls',async()=>{
  const p=await open(h.ids.customer,'#gallery',390);await p.page.waitForTimeout(300);const initial=p.calls.filter(c=>c.action==='download_media').length;assert.ok(initial>0&&initial<24,`Initial image downloads: ${initial}`);await p.page.locator('[data-post]').last().scrollIntoViewIfNeeded();await p.page.waitForTimeout(200);assert.ok(p.calls.filter(c=>c.action==='download_media').length>initial);await p.context.close();
 });
 await check('Upcoming cards distinguish schedule, products and the existing inquiry destination',async()=>{
  const p=await open(h.ids.customer,'#upcoming');await p.page.getByText('Saturday · 9:00 AM',{exact:true}).waitFor();await p.page.getByText('What you will make',{exact:true}).waitFor();assert.equal(await p.page.getByRole('link',{name:'Ask about the workshop',exact:true}).getAttribute('href'),'https://thelittlebakerkitchen.com/contactus.html');await p.context.close();
 });
 await check('Reading an announcement updates its local unread appearance',async()=>{
  const p=await open(h.ids.customer,'#announcements');const card=p.page.locator('.ap-announcement').filter({hasText:'UX unread announcement'});assert.ok(await card.locator('.ap-read-state').getByText('Unread',{exact:true}).isVisible());await card.getByRole('button',{name:'Read announcement →'}).click();await p.page.getByRole('dialog').waitFor();await p.page.getByRole('button',{name:'Close',exact:true}).click();assert.ok(await card.locator('.ap-read-state').getByText('Read',{exact:true}).isVisible());assert.ok((await api(h.ids.customer,'dashboard')).announcements.find(a=>a.id===ann.id).read);await p.context.close();
 });
 await check('Both newsletter controls distinguish saved and unsaved choices without auto-subscribing',async()=>{
  const p=await open(h.ids.customer,'#preferences');for(const scope of ['#ap-newsletter','#ap-kitchen-newsletter']){const form=p.page.locator(scope),save=form.getByRole('button',{name:/Save .*preference/}),box=form.getByRole('checkbox');await save.waitFor();assert.equal(await save.isEnabled(),false);await box.check();assert.equal(await save.isEnabled(),true);await form.getByText('Unsaved changes',{exact:true}).waitFor();if(scope==='#ap-newsletter')assert.equal((await api(h.ids.customer,'dashboard')).academy_newsletter,false);await save.click();await form.getByText('Saved',{exact:true}).waitFor();assert.equal(await save.isEnabled(),false);}assert.equal((await api(h.ids.customer,'dashboard')).academy_newsletter,true);await p.context.close();
 });
 await check('Instructor landing uses teaching navigation and Needs reply remains after reading a question',async()=>{
  const question=await api(h.ids.customer,'start_thread',{class_id:cookie.id,subject:'UX triage question',body:'Needs an answer',recipe_id:recipe.id});await api(h.ids.customer,'send_message',{id:question.id});await api(h.ids.staff,'read_thread',{id:question.thread_id,message_id:question.id});const p=await s.pageFor(h.ids.staff);await p.page.goto(origin+'/academy/admin');await p.page.getByRole('heading',{name:'Instructor Inbox',exact:true}).waitFor();await p.page.getByRole('link',{name:/UX triage question/}).waitFor();assert.equal(await p.page.locator('.ap-sidebar a[href="/academy/dashboard#classes"]').count(),0);assert.equal(await p.page.getByRole('link',{name:'Accounts / Students',exact:true}).count(),0);await p.page.getByRole('button',{name:'Resolved',exact:true}).click();await p.page.getByRole('heading',{name:'No resolved conversations.'}).waitFor();await p.context.close();
 });
 await check('Owner assignment keeps selection count and instructor visible and reports success',async()=>{
  const p=await s.pageFor(h.ids.owner);await p.page.goto(origin+'/academy/admin#accounts');await p.page.getByLabel('Search accounts').fill('customer@example.test');await p.page.getByRole('button',{name:'Search',exact:true}).click();await p.page.getByRole('checkbox',{name:'Select Alice Baker'}).check();await p.page.getByText('1 account selected',{exact:true}).waitFor();await p.page.getByLabel('Class to assign',{exact:true}).selectOption(cupcake.id);await p.page.getByText('Instructor: Chef Cupcake',{exact:true}).waitFor();await p.page.getByRole('button',{name:'Assign selected accounts'}).click();await p.page.getByText('1 class assignments saved.',{exact:true}).waitFor();await p.page.getByText('0 accounts selected',{exact:true}).waitFor();assert.equal(await p.page.getByRole('button',{name:'Assign selected accounts'}).isEnabled(),false);await p.context.close();
 });
 await check('Route changes acknowledge loading immediately and preserve navigation elements',async()=>{
  const p=await open(h.ids.customer,'#classes');await p.page.evaluate(()=>window.uxNav=document.querySelector('.ap-sidebar'));const delay=p.delayNext('class');await p.page.getByRole('link',{name:'Open class',exact:true}).first().click();await delay.pending;await p.page.locator('#ap-route-progress').waitFor();assert.equal(await p.page.locator('#ap-page-content').evaluate(e=>e.inert),true);delay.release();await p.page.getByRole('heading',{name:'Animal Cupcakes',exact:true}).waitFor();assert.equal(await p.page.evaluate(()=>document.querySelector('.ap-sidebar')===window.uxNav),true);await p.context.close();
 });
 assert.deepEqual(s.errors,[]);
}finally{await writeFile(out+'/results.json',JSON.stringify({results,errors:s.errors,scope:'Actual pages and migrated RPCs with synthetic Auth/media transport; installed desktop browser and emulated viewports.'},null,2));await s.close();console.log(JSON.stringify({passed:results.filter(r=>r.status==='PASS').length,failed:results.filter(r=>r.status!=='PASS').length}));if(results.some(r=>r.status!=='PASS'))process.exitCode=1;}
