import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,join,extname,sep} from 'node:path';
import {setup} from '../academy-portal.mjs';
import {validateWebP} from '../../supabase/functions/academy-media/handler.ts';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_PACKAGE_ROOT?join(process.env.PLAYWRIGHT_PACKAGE_ROOT,'playwright'):'playwright');
const state=await setup(),{db,h,api,cookie,cupcake,service}=state;let queue=Promise.resolve(),failUploadOnce=false;
const serialized=fn=>{const next=queue.then(fn,fn);queue=next.catch(()=>{});return next;};
const root=resolve(import.meta.dirname,'../..'),out=join(root,'tests/artifacts/academy-portal'),origin='https://academy.test';await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||(process.platform==='win32'?'chrome':undefined)}),results=[],errors=[],files=new Map();
const original=await readFile('assets/ordering/client.js','utf8');const exportNames=[...original.matchAll(/export\s+(?:async\s+)?(?:function|const|let)\s+(\w+)/g)].map(m=>m[1]);
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.woff2':'font/woff2','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml','.json':'application/json'};
async function pageFor(user,width=1440){
 const context=await browser.newContext({viewport:{width,height:1000}});
 await context.exposeFunction('portalApi',(action,payload)=>serialized(()=>api(user,action,payload)));
 await context.exposeFunction('portalUpload',async({id,bytes})=>serialized(async()=>{if(failUploadOnce){failUploadOnce=false;throw Error('Simulated connection loss');}const data=Uint8Array.from(bytes),dimensions=validateWebP(data);const a=await h.as(user,async()=>(await db.query('select public.academy_portal_upload_check($1) r',[id])).rows[0].r);assert.equal(dimensions.width,a.width);assert.equal(data.length,a.size_bytes);await db.query("insert into storage.objects(bucket_id,name,metadata) values('academy-student-media',$1,$2::jsonb)",[a.path,JSON.stringify({size:data.length,mimetype:'image/webp'})]);files.set(a.path,Buffer.from(data));return service('academy_portal_confirm_upload',[id,user,'a'.repeat(64)]);}));
 await context.exposeFunction('portalMedia',path=>serialized(async()=>{const allowed=await state.storage(user,path);if(!allowed.length)throw Error('Private media');return [...(files.get(path)||Buffer.alloc(0))];}));
 const session=user?{user:{id:user,email: user===h.ids.customer?'customer@example.test':'admin@example.test'}}:null;
 const provided=['ready','configured','initializationError','auth','academyPortalApi','academyPortalMedia','academyPortalUpload','escapeHtml','academyBackupApi','academyBackupConnection'];
 const client=`export const ready=Promise.resolve(),configured=true,initializationError=null,auth={getSession:async()=>({data:{session:${JSON.stringify(session)}}}),onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}}),signOut:async()=>({})};export const academyPortalApi=(a,p={})=>window.portalApi(a,p);export const academyPortalMedia=async p=>new Blob([Uint8Array.from(await window.portalMedia(p))],{type:'image/webp'});export const academyPortalUpload=async(id,file,progress)=>{progress(50);const r=await window.portalUpload({id,bytes:[...new Uint8Array(await file.arrayBuffer())]});progress(100);return r;};export const escapeHtml=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));export const academyBackupApi=async()=>({enabled:false,jobs:[],schedule:'Daily at 02:00 Asia/Manila'});export const academyBackupConnection=async()=>({});${exportNames.filter(n=>!provided.includes(n)).map(n=>`export const ${n}=async()=>({});`).join('\n')}`;
 await context.route('**/*',async route=>{const u=new URL(route.request().url());if(u.origin!==origin)return route.abort();if(u.pathname==='/assets/ordering/client.js')return route.fulfill({contentType:'text/javascript',body:client});
 if(u.pathname==='/assets/ordering/newsletter-client.js')return route.fulfill({contentType:'text/javascript',body:"let status='unsubscribed';export async function newsletterRequest(action){if(action==='subscribe')status='subscribed';if(action==='unsubscribe')status='unsubscribed';return {status};}"});
  let path=u.pathname;if(/^\/academy\/(dashboard|admin|unsubscribe)\/?$/.test(path))path=path.replace(/\/$/,'')+'/index.html';const file=resolve(root,'.'+decodeURIComponent(path));if(!file.startsWith(root+sep))return route.abort();try{await route.fulfill({body:await readFile(file),contentType:mime[extname(file)]||'application/octet-stream'});}catch{await route.fulfill({status:404,body:'Not found'});}});
 const page=await context.newPage();page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));return {page,context};
}
const check=async(name,fn)=>{await fn();results.push({name,status:'PASS'});console.log('PASS',name);};
try{
 await api(h.ids.owner,'save_announcement',{title:'A warm welcome',summary:'Welcome to the kitchen',content:'Make yourself at home.',status:'published'});
 const recipe=await api(h.ids.owner,'save_recipe',{title:'Chocolate Chip Cookies',document:{description:'A crisp edge and a soft centre.',student_notes:'Let the tray cool.',variants:[{name:'Cookie dough',yield:{quantity:'12',unit:'cookies'},groups:[{name:'Dough',ingredients:[{name:'Flour',quantity:'100',unit:'g'}]}],methods:[{name:'Method',steps:[{instruction:'Mix gently. Then bake.'}]}],baking:[],equipment:['Mixing bowl']}]}});await api(h.ids.owner,'assign_recipe',{class_id:cookie.id,recipe_id:recipe.id});
 const anon=await pageFor(null);await check('Logged-out direct URL has login/signup and no protected data',async()=>{await anon.page.goto(origin+'/academy/dashboard');await anon.page.getByRole('heading',{name:'Welcome to TLB Academy'}).waitFor();assert.equal(await anon.page.getByRole('link',{name:'Log In',exact:true}).getAttribute('href'),'/account.html?next=%2Facademy%2Fdashboard');assert.equal(await anon.page.locator('[data-media-id]').count(),0);await anon.page.screenshot({path:join(out,'login-desktop.png'),fullPage:true});});await anon.context.close();
 const none=await pageFor(h.ids.unverified,390);await check('No-class account can browse the gallery and has no instructor/submission controls',async()=>{await none.page.goto(origin+'/academy/dashboard');await none.page.getByRole('heading',{name:"You don't have any Academy classes linked to your account yet."}).waitFor();await none.page.getByRole('link',{name:'Student gallery',exact:true}).click();await none.page.getByRole('heading',{name:'What our students are baking'}).waitFor();assert.equal(await none.page.getByRole('link',{name:'Share what you made',exact:true}).count(),0);assert.ok(await none.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await none.page.screenshot({path:join(out,'empty-gallery-mobile.png'),fullPage:true});});await none.context.close();
 const student=await pageFor(h.ids.customer);await check('Assigned class opens recipe; online tablet presentation has no download controls',async()=>{await student.page.goto(origin+'/academy/dashboard');await student.page.getByRole('link',{name:'Open class',exact:true}).click();await student.page.getByRole('heading',{name:'Cookies & Brownies',exact:true}).waitFor();await student.page.getByRole('link',{name:'Chocolate Chip Cookies Open recipe →'}).click();await student.page.getByRole('heading',{name:'Chocolate Chip Cookies'}).waitFor();await student.page.getByRole('button',{name:'Ingredients',exact:true}).click();await student.page.getByRole('cell',{name:'Flour',exact:true}).waitFor();assert.equal(await student.page.getByRole('button',{name:/download|print|export/i}).count(),0);await student.page.setViewportSize({width:820,height:1100});assert.ok(await student.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await student.page.screenshot({path:join(out,'recipe-tablet.png'),fullPage:true});});
 const png=await student.page.evaluate(()=>{const c=document.createElement('canvas');c.width=200;c.height=150;const x=c.getContext('2d');x.fillStyle='#d4aa75';x.fillRect(0,0,200,150);x.fillStyle='#75441e';for(let i=0;i<7;i++){x.beginPath();x.arc(25+i*24,40+i%2*45,7,0,7);x.fill();}return c.toDataURL('image/png').split(',')[1];});const fixture=join(out,'fixture-cookie.png');await writeFile(fixture,Buffer.from(png,'base64'));
 await check('Mobile multiple-photo submission shows visibility and enters moderation',async()=>{await student.page.setViewportSize({width:390,height:844});await student.page.goto(origin+`/academy/dashboard#share/${cookie.id}`);await student.page.getByLabel('Product / title').fill('My chocolate chip cookies');await student.page.getByLabel('Caption',{exact:true}).fill('A little crisp around the edges.');await student.page.locator('input[name=photos]').setInputFiles([{name:'first.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')},{name:'second.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')}]);await student.page.getByRole('button',{name:'Submit your creation'}).click();await student.page.waitForURL('**/#class/**',{timeout:15000}).catch(async()=>{await student.page.waitForFunction(()=>location.hash.startsWith('#class/'));});await student.page.getByText('Pending approval',{exact:true}).waitFor();assert.ok(await student.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));});
 const teacher=await pageFor(h.ids.staff);await check('Assigned instructor approves work and it appears to a no-class account',async()=>{await teacher.page.goto(origin+'/academy/admin#moderation');await teacher.page.getByRole('button',{name:'Approve',exact:true}).click();await teacher.page.getByRole('heading',{name:'Nothing waiting here.'}).waitFor();const viewer=await pageFor(h.ids.unverified);await viewer.page.goto(origin+'/academy/dashboard#gallery');await viewer.page.getByRole('heading',{name:'My chocolate chip cookies'}).waitFor();await viewer.page.waitForFunction(()=>document.querySelector('[data-media-id]')?.naturalWidth>0);await viewer.page.getByRole('button',{name:'View My chocolate chip cookies'}).click();assert.equal(await viewer.page.locator('dialog img').count(),2);await viewer.context.close();});
 await check('Question with multiple photos, private instructor reply, and unread indicators',async()=>{await student.page.goto(origin+`/academy/dashboard#ask/${cookie.id}`);await student.page.getByLabel('Subject',{exact:true}).fill('Why are the edges dark?');await student.page.getByLabel('Message',{exact:true}).fill('Should I lower the temperature?');await student.page.locator('input[name=photos]').setInputFiles([{name:'first.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')},{name:'second.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')}]);await student.page.getByRole('button',{name:'Send private message'}).click();await student.page.waitForFunction(()=>location.hash.startsWith('#thread/'));await student.page.getByRole('heading',{name:'Why are the edges dark?'}).waitFor();await teacher.page.goto(origin+'/academy/admin#inbox');await teacher.page.getByRole('link',{name:/Why are the edges dark/}).click();await teacher.page.getByLabel('Your reply').fill('Try lowering the oven temperature slightly.');await teacher.page.getByRole('button',{name:'Send reply',exact:true}).click();await teacher.page.getByText('Try lowering the oven temperature slightly.',{exact:true}).waitFor();await student.page.goto(origin+'/academy/dashboard#messages');await student.page.getByText('1 new',{exact:true}).waitFor();await student.page.getByRole('link',{name:/Why are the edges dark/}).click();await student.page.getByText('Try lowering the oven temperature slightly.',{exact:true}).waitFor();await student.page.screenshot({path:join(out,'private-message-mobile.png'),fullPage:true});});
 const owner=await pageFor(h.ids.owner);await check('Admin class, module, account assignment and announcement controls save through real APIs',async()=>{await owner.page.goto(origin+'/academy/admin#classes/new');await owner.page.getByLabel('Class name',{exact:true}).fill('QA Bread');await owner.page.getByLabel('Primary instructor').selectOption(h.ids.staff);await owner.page.getByLabel('Status',{exact:true}).selectOption('active');await owner.page.getByRole('button',{name:'Save changes',exact:true}).click();await owner.page.getByRole('button',{name:'Add module'}).waitFor();await owner.page.getByRole('button',{name:'Add module'}).click();await owner.page.getByLabel('Module name').fill('First dough');await owner.page.locator('dialog').getByRole('button',{name:'Save changes'}).click();await owner.page.getByText('1. First dough',{exact:true}).waitFor();await owner.page.goto(origin+'/academy/admin#accounts');await owner.page.getByLabel('Search accounts').fill('customer@example.test');await owner.page.getByRole('button',{name:'Search',exact:true}).click();await owner.page.getByRole('checkbox',{name:'Select Alice Baker'}).check();await owner.page.locator('#ap-assign-class').selectOption({label:'QA Bread'});await owner.page.getByRole('button',{name:'Assign selected accounts'}).click();await owner.page.getByText('1 class assignments saved.',{exact:true}).waitFor();});

 await check('Structured student recipe editing preserves groups and method details',async()=>{const rich=await api(h.ids.owner,'save_recipe',{title:'Rich teaching recipe',document:{student_notes:'Keep notes',student_tips:'Keep tips',variants:[{name:'Cake',yield:{quantity:'1',unit:'cake'},groups:[{name:'Wet',ingredients:[{name:'Egg',quantity:'2',unit:'pcs',brand:'Approved'}]},{name:'Dry',ingredients:[{name:'Flour',quantity:'1/2',unit:'cup'}]}],methods:[{name:'Mix',steps:[{instruction:'Fold gently.\nKeep the air.',temperature:'22 C',timer_minutes:'3',equipment:'Spatula'}]}],equipment:['Bowl'],baking:[{name:'Oven',top:'160',bottom:'150',fan:'off',minutes:'20',core:'90'}]}]}});await owner.page.goto(origin+'/academy/admin#recipes/'+rich.id);await owner.page.getByLabel('Recipe title',{exact:true}).fill('Rich teaching recipe edited');await owner.page.getByRole('button',{name:'Save student recipe',exact:true}).click();await owner.page.getByText('Independent student recipe version saved.',{exact:true}).waitFor();const saved=await api(h.ids.owner,'admin_recipe',{id:rich.id});assert.deepEqual(saved.document,rich.document);assert.equal(saved.versions.length,2);});
 await check('Failed photo upload can retry and publish one private submission',async()=>{await student.page.goto(origin+'/academy/dashboard#share/'+cookie.id);await student.page.getByLabel('Product / title').fill('Private retry check');await student.page.getByRole('radio',{name:/Private to Instructor/}).check();await student.page.locator('input[name=photos]').setInputFiles({name:'retry.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});failUploadOnce=true;await student.page.getByRole('button',{name:'Submit your creation'}).click();await student.page.getByRole('button',{name:'Retry upload & send'}).click();await student.page.waitForFunction(()=>location.hash.startsWith('#class/'));await student.page.getByRole('button',{name:'Private retry check',exact:true}).click();await student.page.locator('dialog img').waitFor();const counts=await db.query("select (select count(*) from tlb.academy_submissions where title='Private retry check') submissions,(select count(*) from tlb.academy_portal_media m join tlb.academy_submissions s on s.id=m.submission_id where s.title='Private retry check') media");assert.equal(Number(counts.rows[0].submissions),1);assert.equal(Number(counts.rows[0].media),1);await student.page.getByRole('button',{name:'Close',exact:true}).click();});
 await check('Academy newsletter control saves independently and instructor can resolve a conversation',async()=>{await student.page.goto(origin+'/academy/dashboard#preferences');await student.page.getByRole('button',{name:'Save email preference',exact:true}).waitFor();for(const width of [1440,390]){await student.page.setViewportSize({width,height:900});const styles=await student.page.evaluate(()=>{const a=document.querySelector('#ap-newsletter button[type=submit]'),b=document.querySelector('#ap-kitchen-newsletter button[type=submit]');return [a,b].map(el=>({background:getComputedStyle(el).backgroundColor,border:getComputedStyle(el).borderRadius,width:el.getBoundingClientRect().width,y:el.getBoundingClientRect().y,height:el.getBoundingClientRect().height}));});assert.equal(styles[0].background,styles[1].background);assert.equal(styles[0].border,styles[1].border);assert.equal(styles[0].height,styles[1].height);if(width>760)assert.ok(Math.abs(styles[0].y-styles[1].y)<2);assert.ok(styles[1].width>240);assert.ok(await student.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await student.page.screenshot({path:join(out,'preferences-'+width+'.png'),fullPage:true});}await student.page.getByRole('checkbox',{name:'Send me Academy news and promotions'}).check();await student.page.getByRole('button',{name:'Save Academy preference'}).click();await student.page.getByText('Your Academy newsletter preference is saved.',{exact:true}).waitFor();assert.equal((await api(h.ids.customer,'dashboard')).academy_newsletter,true);await teacher.page.goto(origin+'/academy/admin#inbox');await teacher.page.getByRole('button',{name:'All',exact:true}).click();await teacher.page.getByRole('link',{name:/Why are the edges dark/}).click();await teacher.page.getByRole('button',{name:'Mark resolved',exact:true}).click();await teacher.page.getByRole('button',{name:'Reopen conversation',exact:true}).waitFor();});
 await check('Desktop, tablet and mobile dashboard layout',async()=>{for(const width of [1440,820,390]){await student.page.setViewportSize({width,height:1000});await student.page.goto(origin+'/academy/dashboard');await student.page.getByRole('heading',{name:'Welcome, Alice.'}).waitFor();assert.ok(await student.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await student.page.screenshot({path:join(out,`dashboard-${width}.png`),fullPage:true});}});
 await check('Recipe ingredients fit a phone and revoked access clears an open private dialog',async()=>{await student.page.setViewportSize({width:390,height:844});await student.page.goto(origin+'/academy/dashboard#recipe/'+cookie.id+'/'+recipe.id);await student.page.getByRole('button',{name:'Ingredients',exact:true}).click();assert.ok(await student.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await student.page.goto(origin+'/academy/dashboard#class/'+cookie.id);await student.page.getByRole('button',{name:'Private retry check',exact:true}).click();await student.page.locator('dialog').waitFor();const account=await api(h.ids.owner,'account',{id:h.ids.customer});await api(h.ids.owner,'revoke',{id:account.enrollments.find(e=>e.class_id===cookie.id&&e.status==='active').id});await student.page.evaluate(()=>window.dispatchEvent(new Event('focus')));await student.page.getByRole('heading',{name:'Academy is unavailable right now.'}).waitFor();assert.equal(await student.page.locator('dialog').count(),0);assert.equal(await student.page.locator('[data-media-id]').count(),0);});
 assert.deepEqual(errors,[]);await student.context.close();await teacher.context.close();await owner.context.close();
}catch(e){for(const context of browser.contexts())for(const page of context.pages()){await writeFile(join(out,'failure-body.txt'),await page.locator('body').innerText()).catch(()=>{});await page.screenshot({path:join(out,'failure.png'),fullPage:true}).catch(()=>{});console.error('PAGE',page.url(),(await page.locator('body').innerText()).slice(-2500));}console.error('FAIL',e.message);results.push({name:'Browser integration',status:'ISSUE REMAINS',error:e.message});process.exitCode=1;}finally{await writeFile(join(out,'browser-results.json'),JSON.stringify({results,errors},null,2));await browser.close();await db.close();}
