import assert from 'node:assert/strict';import {readFile,writeFile,mkdir} from 'node:fs/promises';import {createRequire} from 'node:module';import {join,resolve,extname,sep} from 'node:path';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_PACKAGE_ROOT?join(process.env.PLAYWRIGHT_PACKAGE_ROOT,'playwright'):'playwright'),root=resolve(import.meta.dirname,'../..'),origin='https://academy.test';
const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||(process.platform==='win32'?'chrome':undefined)}),context=await browser.newContext(),results=[];
const provided=['ready','configured','initializationError','auth','authLink','api','escapeHtml','money','formatDate','toast'];
const exports=[...(await readFile('assets/ordering/client.js','utf8')).matchAll(/export\s+(?:async\s+)?(?:function|const|let)\s+(\w+)/g)].map(m=>m[1]);
const client=`export const ready=Promise.resolve(),configured=true,initializationError=null,authLink={received:true,failed:false,type:'signup'};
const user={id:'11111111-1111-4111-8111-111111111111',email:'fixture@example.test',email_confirmed_at:'2026-01-01'};
const capture=(name,v)=>{localStorage.setItem(name,JSON.stringify(v));return {data:{session:location.search.includes('immediate=1')?{user}:null},error:null};};
export const auth={getSession:async()=>({data:{session:null}}),getUser:async()=>({data:{user:(location.pathname.includes('auth-callback')||location.search.includes('profile=1'))?user:null}}),onAuthStateChange:()=>({}),signInWithPassword:async v=>capture('signin',v),signUp:async v=>capture('signup',v),resetPasswordForEmail:async(email,options)=>capture('reset',{email,options}),resend:async v=>capture('resend',v)};
export const api=async a=>a==='my_orders'?[]:{};export const escapeHtml=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));export const money=v=>String(v),formatDate=v=>String(v),toast=()=>{};
${exports.filter(n=>!provided.includes(n)).map(n=>`export const ${n}=async()=>({});`).join('\n')}`;
await context.route('**/*',async route=>{const u=new URL(route.request().url());if(u.origin!==origin)return route.abort();if(u.pathname==='/assets/ordering/client.js')return route.fulfill({contentType:'text/javascript',body:client});if(['/academy/dashboard','/shop.html'].includes(u.pathname))return route.fulfill({contentType:'text/html',body:'<h1>Authentication return destination</h1>'});const file=resolve(root,'.'+u.pathname);if(!file.startsWith(root+sep))return route.abort();try{await route.fulfill({body:await readFile(file),contentType:({'.js':'text/javascript','.css':'text/css','.html':'text/html','.png':'image/png','.json':'application/json'})[extname(file)]||'application/octet-stream'});}catch{await route.fulfill({status:404,body:''});}});
const p=await context.newPage();p.setDefaultTimeout(10000);const check=async(name,fn)=>{await fn();results.push({name,status:'PASS (browser/Auth transport fixture)'});console.log('PASS',name);};
try{
 await check('My Profile exposes the Academy card and opens its student dashboard',async()=>{await p.goto(origin+'/account.html?profile=1');const link=p.getByRole('link',{name:'Open Student Dashboard →',exact:true});await link.waitFor();assert.equal(await link.getAttribute('href'),'/academy/dashboard');await link.click();await p.waitForURL(origin+'/academy/dashboard');});
 await check('Existing TLB login returns directly to Academy',async()=>{await p.goto(origin+'/account.html?next=%2Facademy%2Fdashboard');await p.getByLabel('Email address',{exact:true}).fill('fixture@example.test');await p.getByLabel('Password',{exact:true}).fill('Test-password-123');await p.locator('#auth-form button[type=submit]').click();await p.waitForURL(origin+'/academy/dashboard');});
 await check('Signup verification link preserves Academy return across a new browser tab',async()=>{await p.goto(origin+'/account.html?mode=signup&next=%2Facademy%2Fdashboard');await p.getByLabel('Email address',{exact:true}).fill('fixture@example.test');await p.getByLabel('Password',{exact:true}).fill('Test-password-123');await p.getByLabel('Confirm password',{exact:true}).fill('Test-password-123');await p.locator('#auth-form button[type=submit]').click();await p.getByText(/If this address is eligible/).waitFor();const saved=await p.evaluate(()=>JSON.parse(localStorage.getItem('signup')));assert.equal(new URL(saved.options.emailRedirectTo).searchParams.get('next'),'/academy/dashboard');const fresh=await context.newPage();await fresh.goto(saved.options.emailRedirectTo);await fresh.waitForURL(origin+'/academy/dashboard');await fresh.close();});
 await check('Signup with an immediate existing-auth session returns directly to Academy',async()=>{await p.goto(origin+'/account.html?mode=signup&immediate=1&next=%2Facademy%2Fdashboard');await p.getByLabel('Email address',{exact:true}).fill('fixture@example.test');await p.getByLabel('Password',{exact:true}).fill('Test-password-123');await p.getByLabel('Confirm password',{exact:true}).fill('Test-password-123');await p.locator('#auth-form button[type=submit]').click();await p.waitForURL(origin+'/academy/dashboard');});
 await check('Forgot password preserves the Academy destination',async()=>{await p.goto(origin+'/account.html?mode=recover&next=%2Facademy%2Fdashboard');await p.getByLabel('Email address',{exact:true}).fill('fixture@example.test');await p.locator('#auth-form button[type=submit]').click();await p.getByText(/If an account exists for this address/).waitFor();const saved=await p.evaluate(()=>JSON.parse(localStorage.getItem('reset')));assert.equal(new URL(saved.options.redirectTo).searchParams.get('next'),'/academy/dashboard');});
 await check('Authentication return allowlist rejects external and protocol-relative destinations',async()=>{for(const next of ['https://evil.test','//evil.test','/academy/dashboard/../../evil']){await p.goto(origin+'/account.html?next='+encodeURIComponent(next));await p.getByLabel('Email address',{exact:true}).fill('fixture@example.test');await p.getByLabel('Password',{exact:true}).fill('Test-password-123');await p.locator('#auth-form button[type=submit]').click();await p.waitForURL(origin+'/shop.html');}});
}finally{await mkdir('tests/artifacts/academy-portal',{recursive:true});await writeFile('tests/artifacts/academy-portal/auth-results.json',JSON.stringify({results,scope:'Actual account.js and browser navigation with Auth transport fixtures; no hosted accounts or emails created.'},null,2));await browser.close();}
