import {createRequire} from 'node:module';
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import {join,extname,resolve} from 'node:path';
import {once} from 'node:events';
import assert from 'node:assert/strict';
import {dateInManila,addDays} from '../../assets/ordering/shop-rules.js';
const screenshotDir=process.env.UI_SCREENSHOT_DIR;
const shot=async(page,name,options={})=>{if(screenshotDir)await page.screenshot({path:join(screenshotDir,name),...options})};
const require=createRequire(import.meta.url);const {chromium}=require(process.env.PLAYWRIGHT_PACKAGE_ROOT?join(process.env.PLAYWRIGHT_PACKAGE_ROOT,'playwright'):'playwright');
const root=resolve(import.meta.dirname,'../..');
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.webp':'image/webp','.jpg':'image/jpeg','.jpeg':'image/jpeg','.woff2':'font/woff2','.md':'text/markdown'};
const server=createServer(async(req,res)=>{const name=decodeURIComponent(new URL(req.url,'http://localhost').pathname);const path=resolve(root,'.'+(name==='/'?'/index.html':name));try{if(!path.startsWith(root+'/'))throw Error();const data=await readFile(path);res.writeHead(200,{'Content-Type':mime[extname(path)]||'application/octet-stream'});res.end(data)}catch{res.writeHead(404);res.end('Not found')}}).listen(0,'127.0.0.1');await once(server,'listening');
const origin=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({executablePath:process.env.BROWSER_EXECUTABLE_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage'],headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto(origin+'/shop.html?demo=1',{waitUntil:'networkidle'});
 assert.equal(await page.locator('.product-card').count(),4);
 await shot(page,'shop-desktop.png',{ fullPage:true });
 await page.setViewportSize({width:390,height:844});
 await shot(page,'shop-mobile.png',{ fullPage:true });
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);
 await page.setViewportSize({width:1440,height:1000});
 await page.locator('#fulfillment-date').fill(addDays(dateInManila(),7));
 await page.locator('[data-product="demo-cookie"]').click();
 await page.locator('[data-choice="classic"]').fill('4');await page.locator('[data-choice="matcha"]').fill('2');
 assert.match(await page.locator('#detail-price').innerText(),/660\.00/);
 await shot(page,'product-desktop.png',{  });
 await page.locator('#add-to-cart').click();
 assert.match(await page.locator('#cart').innerText(),/60\.00 per unit/);
 await page.locator('#checkout-button').click();
 await page.locator('[name="buyer_name"]').fill('Demo Buyer');await page.locator('[name="buyer_email"]').fill('demo@example.test');await page.locator('[name="buyer_phone"]').fill('09170000000');
 await page.locator('#review-order').click();
 assert.match(await page.locator('#checkout-title').innerText(),/sweetness/);
 assert.equal(await page.locator('#place-order').isDisabled(),true);
 await shot(page,'checkout-desktop.png',{  });
 await page.locator('#checkout-dialog .close-button').click();
 await page.locator('[data-method="delivery"]').click();await page.locator('#checkout-button').click();
 await page.locator('[name="recipient_name"]').fill('Demo Recipient');await page.locator('[name="recipient_phone"]').fill('09170000001');await page.locator('[name="locality"]').selectOption('Sample City / Sample Barangay');await page.locator('[name="line1"]').fill('123 Demo Street');
 await page.locator('#review-order').click();assert.match(await page.locator('#place-order').innerText(),/810\.00/);
 await page.goto(origin+'/manage.html',{waitUntil:'networkidle'});
 await shot(page,'manage-desktop.png',{ fullPage:true });
 for(const view of ['orders','products','inventory','promos','settings','team']){await page.locator(`[data-view="${view}"]`).click();assert.ok((await page.locator('#workspace').innerText()).length>100)}
 await page.locator('[data-view="products"]').click();await page.getByRole('button',{name:'Add product',exact:false}).first().click();await shot(page,'product-admin.png',{  });
 await page.locator('#dialog-close').click();await page.setViewportSize({width:390,height:844});await shot(page,'manage-mobile.png',{ fullPage:true });assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);
 await page.goto(origin+'/account.html',{waitUntil:'networkidle'});await shot(page,'account-mobile.png',{ fullPage:true });assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);
 await page.goto(origin+'/shop.html',{waitUntil:'networkidle'});assert.equal(await page.locator('.product-card').count(),0);assert.match(await page.locator('#app').innerText(),/backend setup pending/);
 assert.deepEqual(errors,[]);
 console.log('PASS: sample pickup and delivery checkout, 4+2 cookie pricing, surcharge visibility, paused submission, all staff sections, empty real catalogue, 390px layout, no page errors.');
}finally{await browser.close();server.close()}
